name: Deploy Shopify Theme

on:
  push:
    branches:
      - main

jobs:
  deploy-theme:
    name: Push & (optionally) Publish Theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli